services:
  db:
    image: postgres:15
    networks:
      - nt-coaching-infra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    networks:
      - nt-coaching-infra

networks:
  nt-coaching-infra:
    name: nt-coaching-infra
volumes:
  postgres_data:
